question_data = [
    {"category": "Entertainment: Music", "type": "multiple", "difficulty": "medium",
     "question": "Who is the primary lyricist for Canadian progressive rock band Rush?",
     "correct_answer": "Neil Peart",
     "incorrect_answers": ["Geddy Lee", "Alex Lifeson", "John Rutsey"]},
    {"category": "Entertainment: Comics", "type": "multiple", "difficulty": "medium",
     "question": "Who wrote the Batman comic series &quot;The Killing Joke&quot;?",
     "correct_answer": "Alan Moore",
     "incorrect_answers": ["Bill Finger", "Frank Miller", "Jerry Siegel"]},
    {"category": "Vehicles", "type": "multiple", "difficulty": "medium",
     "question": "Volkswagen&#039;s legendary VR6 engine has cylinders positioned at what degree angle?",
     "correct_answer": "15 Degree",
     "incorrect_answers": ["30 Degree", "45 Degree", "90 Degree"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "hard",
     "question": "Released in 2001, the first edition of Apple&#039;s Mac OS X operating system (version 10.0) was given what animal code name?",
     "correct_answer": "Cheetah", "incorrect_answers": ["Puma", "Tiger", "Leopard"]},
    {"category": "Art", "type": "multiple", "difficulty": "medium",
     "question": "Who designed the Chupa Chups logo?",
     "correct_answer": "Salvador Dali",
     "incorrect_answers": ["Pablo Picasso", "Andy Warhol", "Vincent van Gogh"]},
    {"category": "Entertainment: Music", "type": "multiple", "difficulty": "medium",
     "question": "Which song previously recorded by Elvis Presley was covered by UB40 with a reggae beat?",
     "correct_answer": "Can&#039;t Help Falling in Love",
     "incorrect_answers": ["Jailhouse Rock", "In the Ghetto", "Wooden Heart"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "There are 2 player roles in Trouble in Terrorist Town.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "multiple",
     "difficulty": "hard",
     "question": "Who was the Director of the 1988 Anime film &quot;Grave of the Fireflies&quot;?",
     "correct_answer": "Isao Takahata",
     "incorrect_answers": ["Hayao Miyazaki", "Satoshi Kon", "Sunao Katabuchi"]},
    {"category": "Science & Nature", "type": "multiple", "difficulty": "hard",
     "question": "In physics, conservation of energy and conservation of momentum are both consequences of which of the following?",
     "correct_answer": "Noether&#039;s Theorem",
     "incorrect_answers": ["Bell&#039;s Theorem", "Wick&#039;s Theorem",
                           "Carnot&#039;s Theorem"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "The shotgun appears in every numbered Resident Evil game.",
     "correct_answer": "True", "incorrect_answers": ["False"]}

]
