"""
3474. Lexicographically Smallest Generated String
Hard
Topics
premium lock icon
Companies
Hint
You are given two strings, str1 and str2, of lengths n and m, respectively.

A string word of length n + m - 1 is defined to be generated by str1 and str2 if it satisfies the following conditions for each index 0 <= i <= n - 1:

If str1[i] == 'T', the substring of word with size m starting at index i is equal to str2, i.e., word[i..(i + m - 1)] == str2.
If str1[i] == 'F', the substring of word with size m starting at index i is not equal to str2, i.e., word[i..(i + m - 1)] != str2.
Return the lexicographically smallest possible string that can be generated by str1 and str2. If no string can be generated, return an empty string "".

 

Example 1:

Input: str1 = "TFTF", str2 = "ab"

Output: "ababa"

Explanation:

The table below represents the string "ababa"
Index	T/F	Substring of length m
0	'T'	"ab"
1	'F'	"ba"
2	'T'	"ab"
3	'F'	"ba"
The strings "ababa" and "ababb" can be generated by str1 and str2.

Return "ababa" since it is the lexicographically smaller string.

Example 2:

Input: str1 = "TFTF", str2 = "abc"

Output: ""

Explanation:

No string that satisfies the conditions can be generated.

Example 3:

Input: str1 = "F", str2 = "d"

Output: "a"

 

Constraints:

1 <= n == str1.length <= 104
1 <= m == str2.length <= 500
str1 consists only of 'T' or 'F'.
str2 consists only of lowercase English characters.
"""

class Solution:
    def generateString(self, str1: str, str2: str) -> str:
        n, m = len(str1), len(str2)
        L = n + m - 1
        res = ['a'] * L
        locked = [False] * L

        # Step 1: Stamp str2 at all 'T' positions (take max to respect prior stamps)
        for i, c in enumerate(str1):
            if c == 'T':
                for j in range(m):
                    res[i + j] = max(res[i + j], str2[j])
                    locked[i + j] = True

        # Step 2: For each 'F', ensure a mismatch exists
        for i, c in enumerate(str1):
            if c == 'F':
                # Check if already broken by prior stamps
                if any(res[i + j] != str2[j] for j in range(m)):
                    continue

                # Break at the LAST unlocked position (maximizes carry-over
                # to future F windows → lex smallest result)
                broke = False
                for j in range(m - 1, -1, -1):
                    pos = i + j
                    if not locked[pos]:
                        res[pos] = 'b' if str2[j] == 'a' else 'a'
                        broke = True
                        break

                if not broke:
                    return ""  # All positions locked but still match → impossible

        # Step 3: Final verification
        for i, c in enumerate(str1):
            window = ''.join(res[i:i + m])
            if c == 'T' and window != str2:
                return ""
            if c == 'F' and window == str2:
                return ""

        return ''.join(res)

            
            
if __name__ == "__main__":
    solution = Solution()
    print(solution.generateString("TFTF", "ab"))  # Output: "ababa"
    print(solution.generateString("TFTF", "abc"))  # Output: ""
    print(solution.generateString("F", "d"))       # Output: "a"